name: Trigger

on:
  push:
    branches: [master]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: thoth-station/jupyter-notebooks
          submodules: true
          token: ${{ secrets.GITHUB_REPO_TOKEN }}
          ssh-key: ${{ secrets.GITHUB_REPO_SSH_KEY }}

      - name: Update submodule
        run: |-
          git submodule update --init --remote minimal-notebook

      - name: Create Pull Request
        id: pull_request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_REPO_TOKEN }}
          title: "Automatic update of s2i-minimal-notebook"
          body: |-
            The update has been triggered by commit [${{ github.sha }}][0]

            See the workflow run: [${{ github.run_id }}][1]

            [0]: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            [1]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          branch: update/s2i-minimal-notebook
          labels: update, bot, s2i-minimal-notebook
          team-reviewers: owners, maintainers
      - name: Check outputs
        run: |
          echo "Pull Request created: ${{ steps.pull_request.outputs.pr_number }}"
